apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "currents.director.fullname" . }}
  labels:
    {{- include "currents.labels" (dict "context" . "component" .Values.director.name) | nindent 4 }}
spec:
  replicas: {{ .Values.director.replicas }}
  selector:
    matchLabels:
      {{- include "currents.selectorLabels" (dict "context" . "component" .Values.director.name) | nindent 6 }}
  {{- if .Values.director.deploymentStrategy }}
  strategy:
    {{- toYaml .Values.director.deploymentStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "currents.labels" (dict "context" . "component" .Values.director.name) | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "currents.serviceAccountName" . }}
      {{- with .Values.global.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Values.director.name }}
          {{- with .Values.global.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ template "currents.image" (dict "context" . "imageRoot" .Values.director.image) }}
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.director.image.pullPolicy }}
          env:
            - name: ON_PREM_MODE
              value: "true"
            - name: APP_BASE_URL
              value: {{ .Values.currents.baseUrl | quote }}
          {{- if .Values.currents.gitlab.state.secretName }}
            - name: GITLAB_STATE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.currents.gitlab.state.secretName }}
                  key: {{ .Values.currents.gitlab.state.secretKey }}
          {{- end }}
          {{- include "currents.connectionConfigEnv" . | nindent 12 }}
          {{- include "currents.URLConfigEnv" . | nindent 12 }}
          {{- if .Values.currents.apiInternalToken.secretName }}
            - name: API_URL
              value: http://{{ include "currents.server.fullname" . }}/api/v1
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.currents.apiInternalToken.secretName }}
                  key: {{ .Values.currents.apiInternalToken.key }}
          {{- end }}
          {{- with (concat .Values.global.env .Values.director.env) }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.director.service.port }}
              protocol: TCP
          {{- with .Values.director.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.director.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.director.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.global.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.director.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.global.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.director.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.director.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.director.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.director.affinity | default .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
