{{- $generalSet := and (hasKey .Values.currents.ingress "enabled") (kindIs "bool" .Values.currents.ingress.enabled) -}}
{{- $localSet := and (hasKey .Values.director.ingress "enabled") (kindIs "bool" .Values.director.ingress.enabled) -}}
{{- if or (and $localSet .Values.director.ingress.enabled) (and $generalSet .Values.currents.ingress.enabled) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "currents.director.fullname" . }}
  labels:
    {{- include "currents.labels" (dict "context" . "component" .Values.director.name) | nindent 4 }}
  {{- with .Values.director.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.server.ingress.className | default .Values.global.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.director.ingress.tls }}
  tls:
    {{- range .Values.director.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ (tpl . $) | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.director.ingress.hosts }}
    - host: {{ (tpl .host $) | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                {{- if .serviceName }}
                name: {{ .serviceName }}
                {{- else }}
                name: {{ include "currents.director.fullname" $ }}
                {{- end }}
                port:
                  {{- if .servicePortName }}
                  name: {{ .servicePortName }}
                  {{- else }}
                  number: {{ $.Values.director.service.port }}
                  {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
