apiVersion: v1
kind: Service
metadata:
  name: {{ include "currents.director.fullname" . }}
  labels:
    {{- include "currents.labels" (dict "context" . "component" .Values.director.name) | nindent 4 }}
spec:
  type: {{ .Values.director.service.type }}
  ports:
    - port: {{ .Values.director.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "currents.selectorLabels" (dict "context" . "component" .Values.director.name) | nindent 4 }}
