apiVersion: v2
name: currents
description: A Helm chart for Deploying Currents
home: https://currents.dev
type: application
# The chart version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.0
# Version number of the application being deployed.
# Versions are not expected to follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "2025-04-23-001"
maintainers:
  - name: Currents-dev
    url: https://currents.dev
dependencies:
  - name: redis
    version: 20.2.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
