global:
  # Reference to one or more secrets to be used when pulling images.
  # For more information, see [Pull an Image from a Private Registry](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/).
  #
  # For example:
  imagePullSecrets:
    - name: "currents-pull-secret"
  imagePullPolicy: IfNotPresent

currents:
  apiJwtToken:
    secretName: currents-api-jwt-token
  gitlab:
    state:
      secretName: currents-gitlab-key 
      secretKey: gitlab-key.pem
  mongoConnection:
    secretName: mongodb-currents-currents-user
    key: connectionString.standardSrv
  imageTag: staging-aarch64
  elastic:
    tls:
      enabled: false
    host: elasticsearch-es-http
    admin:
      secretName: elasticsearch-es-elastic-user 
      secretKey: elastic

redis:
  enabled: true