---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "currents.scheduler.fullname" . }}-startup-tmp
  labels:
    {{- include "currents.labels" (dict "context" . "component" .Values.scheduler.name) | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.scheduler.startup.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.scheduler.startup.persistence.size | quote }}
{{- if .Values.scheduler.startup.persistence.volumeName }}
  volumeName: {{ .Values.scheduler.startup.persistence.volumeName }}
{{- end }}
{{- if .Values.scheduler.startup.persistence.storageClass }}
  storageClassName: "{{ .Values.scheduler.startup.persistence.storageClass }}"
{{- end }}
  selector:
{{- if .Values.scheduler.startup.persistence.matchLabels }}
    matchLabels:
      {{- toYaml .Values.scheduler.startup.persistence.matchLabels | nindent 6 }}
{{- end -}}
{{- if .Values.scheduler.startup.persistence.matchExpressions }}
    matchExpressions:
      {{- toYaml .Values.scheduler.startup.persistence.matchExpressions | nindent 6 }}
{{- end -}}

