[changelog]
header = "# Changelog\n"
body = """
## [{{ version }}](https://github.com/currents-dev/helm-charts/releases/tag/{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}

### {{ group }}
{% for commit in commits -%}
- [`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/currents-dev/helm-charts/commit/{{ commit.id }}) {{ commit.message | split(pat="\n") | first | trim }}
{% endfor %}
{%- endfor %}
"""
footer = ""
trim = false

[git]
conventional_commits = false
filter_unconventional = true
commit_parsers = [
  { message = "^(\\[.*\\]\\s*)?feat", group = "Features" },
  { message = "^(\\[.*\\]\\s*)?fix", group = "Bug Fixes" },
]
filter_commits = true
tag_pattern = "currents-[0-9].*"
