---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 2
  type: ReplicaSet
  version: "7.0.17"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: cluster-admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongo-admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: admin-scram
    - name: currents-user
      db: currents
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongo-currents-password
      roles:
        - name: dbOwner
          db: currents
      scramCredentialsSecretName: currents-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-admin-password
type: Opaque
stringData:
  password: "password1234"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-currents-password
type: Opaque
stringData:
  password: "password1234"