apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "currents.server.fullname" . }}
  labels:
    {{- include "currents.labels" (dict "context" . "component" .Values.server.name) | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      {{- include "currents.selectorLabels" (dict "context" . "component" .Values.server.name) | nindent 6 }}
  {{- if .Values.server.deploymentStrategy }}
  strategy:
    {{- toYaml .Values.server.deploymentStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "currents.labels" (dict "context" . "component" .Values.server.name) | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "currents.serviceAccountName" . }}
      {{- with .Values.global.SecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Values.server.name }}
          {{- with .Values.global.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ template "currents.image" (dict "context" . "imageRoot" .Values.server.image) }}
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.server.image.pullPolicy }}
          env:
            - name: INCLUDE_DASHBOARD
              value: "onprem"
            - name: ON_PREM_MODE
              value: "true"
          {{- if .Values.currents.gitlab.state.secretName }}
            - name: GITLAB_STATE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.currents.gitlab.state.secretName }}
                  key: {{ .Values.currents.gitlab.state.secretKey }}
          {{- end }}
            - name: JWT_SECRET_EXPIRY
              value: {{ .Values.currents.apiJwtToken.expiry | quote }}
          {{- include "currents.connectionConfigEnv" . | nindent 12 }}
          {{- if .Values.currents.apiJwtToken.secretName }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.currents.apiJwtToken.secretName }}
                  key: {{ .Values.currents.apiJwtToken.key }}
          {{- end }}
          {{- if .Values.currents.apiInternalToken.secretName }}
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.currents.apiInternalToken.secretName }}
                  key: {{ .Values.currents.apiInternalToken.key }}
          {{- end }}
          {{- with (concat .Values.global.env .Values.server.env) }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          volumeMounts:
            - name: pm2-data
              mountPath: /home/node/.pm2
          {{- with .Values.server.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.global.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: pm2-data
          emptyDir:
            medium: "Memory"
      {{- with .Values.global.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity | default .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
