apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "currents.changestreams.fullname" . }}
  labels:
    {{- include "currents.labels" (dict "context" . "component" .Values.changestreams.name) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "currents.selectorLabels" (dict "context" . "component" .Values.changestreams.name) | nindent 6 }}
  {{- if .Values.changestreams.deploymentStrategy }}
  strategy:
    {{- toYaml .Values.changestreams.deploymentStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "currents.labels" (dict "context" . "component" .Values.changestreams.name) | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "currents.serviceAccountName" . }}
      {{- with .Values.global.SecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Values.changestreams.name }}
          {{- with .Values.global.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ template "currents.image" (dict "context" . "imageRoot" .Values.changestreams.image) }}
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.changestreams.image.pullPolicy }}
          env:
            {{- include "currents.connectionConfigEnv" . | nindent 12 }}
            {{- include "currents.URLConfigEnv" . | nindent 12 }}
            {{- with (concat .Values.global.env .Values.changestreams.env) }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.changestreams.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.changestreams.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.changestreams.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.global.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.changestreams.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- with .Values.global.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.changestreams.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.changestreams.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.changestreams.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.changestreams.affinity | default .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
