apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "currents.webhooks.fullname" . }}
  labels:
    {{- include "currents.labels" (dict "context" . "component" .Values.webhooks.name) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "currents.selectorLabels" (dict "context" . "component" .Values.webhooks.name) | nindent 6 }}
  {{- if .Values.webhooks.deploymentStrategy }}
  strategy:
    {{- toYaml .Values.webhooks.deploymentStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "currents.labels" (dict "context" . "component" .Values.webhooks.name) | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "currents.serviceAccountName" . }}
      {{- with .Values.global.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Values.webhooks.name }}
          {{- with .Values.global.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "currents.image" (dict "context" . "imageRoot" .Values.webhooks.image) }}
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.webhooks.image.pullPolicy }}
          env:
            - name: CURRENTS_ENV
              value: "onprem"
            {{- include "currents.connectionConfigEnv" . | nindent 12 }}
            {{- include "currents.URLConfigEnv" . | nindent 12 }}
            {{- include "currents.elasticDataStreamsEnv" . | nindent 12 }}
            {{- with (concat .Values.global.env .Values.webhooks.env) }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: pm2-data
              mountPath: /home/node/.pm2
          {{- with .Values.webhooks.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.webhooks.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.webhooks.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.global.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.webhooks.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: pm2-data
          emptyDir:
            medium: "Memory"
      {{- with .Values.global.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhooks.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhooks.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhooks.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhooks.affinity | default .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
